# Modelling

In [1]:
import numpy as np
from numpy.linalg import matrix_power

In [23]:
#January
january = np.matrix([[0.761,	0,	0.250,	0.250],[0.239,	1,	0.250,	0.250],[0, 0, 0.250, 0.250],[0, 0, 0.250, 0.250]])
print(january)

# ssjan = np.linalg.matrix_power(january, 2)
# print(ssjan)

[[0.761 0.    0.25  0.25 ]
 [0.239 1.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]]


In [4]:
#February
february = np.matrix([[0.714, 0,	0.250,	0.250],[0.286, 0.733, 0.250, 0.250],[0,	0.200,	0.250,	0.250],[0,	0.067,	0.250,	0.250]])
print(february)

[[0.714 0.    0.25  0.25 ]
 [0.286 0.733 0.25  0.25 ]
 [0.    0.2   0.25  0.25 ]
 [0.    0.067 0.25  0.25 ]]


In [5]:
#March
march = np.matrix([[0.440, 0.048, 0, 0], [0.560, 0.429, 0.333, 0], [0, 0.333, 0.333, 0], [0, 0.190, 0.333, 1]])
print(march)

[[0.44  0.048 0.    0.   ]
 [0.56  0.429 0.333 0.   ]
 [0.    0.333 0.333 0.   ]
 [0.    0.19  0.333 1.   ]]


In [6]:
#April
april = np.matrix([[0.167,	0,	0,	0],[0.750,	0.583,	0,	0.167],[0.083,	0.125,	0.500,	0],[0,	0.292,	0.500,	0.833]])
print(april)

[[0.167 0.    0.    0.   ]
 [0.75  0.583 0.    0.167]
 [0.083 0.125 0.5   0.   ]
 [0.    0.292 0.5   0.833]]


In [7]:
#May
may = np.matrix([[0, 0, 0, 0],[1,	0.667,	0.250,	0.063],[0,	0.167,	0.375,	0.250],[0,	0.167,	0.375,	0.688]])
print(may)

[[0.    0.    0.    0.   ]
 [1.    0.667 0.25  0.063]
 [0.    0.167 0.375 0.25 ]
 [0.    0.167 0.375 0.688]]


In [8]:
#June
june = np.matrix([[0.25, 0.143, 0, 0], [0.25, 0.857, 0.727, 0.222], [0.25, 0, 0.273, 0.500], [0.25, 0, 0, 0.278]])
print(june)

[[0.25  0.143 0.    0.   ]
 [0.25  0.857 0.727 0.222]
 [0.25  0.    0.273 0.5  ]
 [0.25  0.    0.    0.278]]


In [9]:
#July
july = np.matrix([[1,	0.233,	0,	0],[0,	0.767,	1,	0.800],[0,	0,	0,	0.200],[0,	0,	0,	0]])
print(july)

[[1.    0.233 0.    0.   ]
 [0.    0.767 1.    0.8  ]
 [0.    0.    0.    0.2  ]
 [0.    0.    0.    0.   ]]


In [10]:
#August
august = np.matrix([[1,	0.359,	0,	0.250],[0,	0.641,	1,	0.250],[0, 0,	0,	0.250],[0,	0,	0,	0.250]])
print(august)

[[1.    0.359 0.    0.25 ]
 [0.    0.641 1.    0.25 ]
 [0.    0.    0.    0.25 ]
 [0.    0.    0.    0.25 ]]


In [11]:
#September
september = np.matrix([[1, 0.923, 0.25,	0.25], [0,	0.077,	0.25,	0.25], [0.000,	0.000,	0.25,	0.25], [0.000,	0.000,	0.25,	0.25]])
print(september)

[[1.    0.923 0.25  0.25 ]
 [0.    0.077 0.25  0.25 ]
 [0.    0.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]]


In [12]:
#October
october = np.matrix([[1,	0.500,	0.250,	0.250],[0,	0.500,	0.250,	0.250],[0,	0,	0.250,	0.250],[0,	0,	0.250,	0.250]])
print(october)

[[1.   0.5  0.25 0.25]
 [0.   0.5  0.25 0.25]
 [0.   0.   0.25 0.25]
 [0.   0.   0.25 0.25]]


In [13]:
#November
november = np.matrix([[0.980,	1,	0.250,	0.250],[0.020,	0,	0.250,	0.250],[0,	0,	0.250,	0.250],[0,	0,	0.250,	0.250]])
print(november)

[[0.98 1.   0.25 0.25]
 [0.02 0.   0.25 0.25]
 [0.   0.   0.25 0.25]
 [0.   0.   0.25 0.25]]


In [14]:
#December
december = np.matrix([[0.938, 0, 0.25, 0.25],[0.063,	1.000,	0.25,	0.25], [0.000,	0.000,	0.25,	0.25], [0.000,	0.000,	0.25,	0.25]])
print(december)

[[0.938 0.    0.25  0.25 ]
 [0.063 1.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]]


In [ ]:
tot=np.matrix([[251/302,	51/208,	0/43,	0/46],[50/302,	124/208,	24/43,	10/46],[1/302,	17/208,	11/43,	14/46],[0/302,	16/208,	8/43,	22/46]])
tottot = np.linalg.matrix_power(tot, 1000)
print(tottot)

[[0.50417362 0.50417362 0.50417362 0.50417362]
 [0.34724541 0.34724541 0.34724541 0.34724541]
 [0.07178631 0.07178631 0.07178631 0.07178631]
 [0.07679466 0.07679466 0.07679466 0.07679466]]
