In [9]:
import pandas as pd
import numpy as np

df = pd.read_csv('monthly.csv', header=None)
array = df.to_numpy()

NDND=[0,0,0,0,0,0,0,0,0,0,0,0]
NDMiD=[0,0,0,0,0,0,0,0,0,0,0,0]
NDMoD=[0,0,0,0,0,0,0,0,0,0,0,0]
NDSED=[0,0,0,0,0,0,0,0,0,0,0,0]
MiDND=[0,0,0,0,0,0,0,0,0,0,0,0]
MiDMiD=[0,0,0,0,0,0,0,0,0,0,0,0]
MiDMoD=[0,0,0,0,0,0,0,0,0,0,0,0]
MiDSED=[0,0,0,0,0,0,0,0,0,0,0,0]
MoDND=[0,0,0,0,0,0,0,0,0,0,0,0]
MoDMiD=[0,0,0,0,0,0,0,0,0,0,0,0]
MoDMoD=[0,0,0,0,0,0,0,0,0,0,0,0]
MoDSED=[0,0,0,0,0,0,0,0,0,0,0,0]
SEDND=[0,0,0,0,0,0,0,0,0,0,0,0]
SEDMiD=[0,0,0,0,0,0,0,0,0,0,0,0]
SEDMoD=[0,0,0,0,0,0,0,0,0,0,0,0]
SEDSED=[0,0,0,0,0,0,0,0,0,0,0,0]

i=0
while(i<=599):
    month=4
    if (array[i][0]==month):
        if (array[i][1]=="Non-drought"):
            if (array[i+1][1]=="Non-drought"):
                NDND[month-1]=NDND[month-1]+1
            elif (array[i+1][1]=="Mild Drought"):
                NDMiD[month-1]=NDMiD[month-1]+1
            elif (array[i+1][1]=="Moderate Drought"):
                NDMoD[month-1]=NDMoD[month-1]+1
            elif (array[i+1][1]=="Severe Drought"):
                NDSED[month-1]=NDSED[month-1]+1
        if (array[i][1]=="Mild Drought"):
            if (array[i+1][1]=="Non-drought"):
                MiDND[month-1]=MiDND[month-1]+1
            elif (array[i+1][1]=="Mild Drought"):
                MiDMiD[month-1]=MiDMiD[month-1]+1
            elif (array[i+1][1]=="Moderate Drought"):
                MiDMoD[month-1]=MiDMoD[month-1]+1
            elif (array[i+1][1]=="Severe Drought"):
                MiDSED[month-1]=MiDSED[month-1]+1
        if (array[i][1]=="Moderate Drought"):
            if (array[i+1][1]=="Non-drought"):
                MoDND[month-1]=MoDND[month-1]+1
            elif (array[i+1][1]=="Mild Drought"):
                MoDMiD[month-1]=MoDMiD[month-1]+1
            elif (array[i+1][1]=="Moderate Drought"):
                MoDMoD[month-1]=MoDMoD[month-1]+1
            elif (array[i+1][1]=="Severe Drought"):
                MoDSED[month-1]=MoDSED[month-1]+1
        if (array[i][1]=="Severe Drought"):
            if (array[i+1][1]=="Non-drought"):
                SEDND[month-1]=SEDND[month-1]+1
            elif (array[i+1][1]=="Mild Drought"):
                SEDMiD[month-1]=SEDMiD[month-1]+1
            elif (array[i+1][1]=="Moderate Drought"):
                SEDMoD[month-1]=SEDMoD[month-1]+1
            elif (array[i+1][1]=="Severe Drought"):
                SEDSED[month-1]=SEDSED[month-1]+1
                
    i=i+1
                
monthlyprob = np.matrix([[NDND[month-1],MiDND[month-1],MoDND[month-1],SEDND[month-1]],
               [NDMiD[month-1],MiDMiD[month-1],MoDMiD[month-1],SEDMiD[month-1]],
               [NDMoD[month-1],MiDMoD[month-1],MoDMoD[month-1],SEDMoD[month-1]],
               [NDSED[month-1],MiDSED[month-1],MoDSED[month-1],SEDSED[month-1]]])
print(monthlyprob)


[[ 2  0  0  0]
 [ 9 14  0  1]
 [ 1  3  4  0]
 [ 0  7  4  5]]


In [11]:
i=0
nd=0
mid=0
mod=0
sed=0
ndnd=0
midmid=0
modmod=0
sedsed=0
while(i<=599):
    if (array[i][1]=="Non-drought"):
        nd=nd+1
        if (array[i+1][1]=="Non-drought"):
            ndnd=ndnd+1
    i=i+1
print(nd)
print(ndnd)            

303
251
